"""Initial migration

Revision ID: 2ef215065e08
Revises: 
Create Date: 2023-07-10 19:22:08.312137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef215065e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Cars'))
    )
    op.create_table('Images',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('file_name', sa.String(length=250), nullable=False),
    sa.Column('MIME', sa.String(length=250), nullable=False),
    sa.Column('MD5', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Images'))
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Roles'))
    )
    op.create_table('SetupFiles',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('file_name', sa.String(length=250), nullable=False),
    sa.Column('MIME', sa.String(length=250), nullable=False),
    sa.Column('MD5', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_SetupFiles'))
    )
    op.create_table('Tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tracks'))
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users')),
    sa.UniqueConstraint('login', name=op.f('uq_Users_login'))
    )
    op.create_table('Setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('condition_track', sa.Integer(), nullable=False),
    sa.Column('condition_air', sa.Integer(), nullable=False),
    sa.Column('downloaded', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['Cars.id'], name=op.f('fk_Setups_car_id_Cars')),
    sa.ForeignKeyConstraint(['track_id'], ['Tracks.id'], name=op.f('fk_Setups_track_id_Tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Setups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Setups')
    op.drop_table('Users')
    op.drop_table('Tracks')
    op.drop_table('SetupFiles')
    op.drop_table('Roles')
    op.drop_table('Images')
    op.drop_table('Cars')
    # ### end Alembic commands ###
